# Generated by Django 5.1.4 on 2026-05-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScraperJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scrape_top", "REST top-feedback (httpx)"),
                            ("scrape_full", "Tólıq pikirler (Playwright)"),
                            ("run_sentiment", "Sentiment analiz"),
                            ("run_absa", "ABSA analiz"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("log", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("products_added", models.PositiveIntegerField(default=0)),
                ("reviews_added", models.PositiveIntegerField(default=0)),
                ("sentiment_analyzed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="scraper_scr_status_78c57e_idx"
                    )
                ],
            },
        ),
    ]
