# Generated by Django 5.1.4 on 2026-05-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="Ключевые слова на uz/ru — триггеры для аспекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аспект",
                "verbose_name_plural": "Аспекты",
            },
        ),
        migrations.CreateModel(
            name="AspectMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("positive", "Позитив"),
                            ("neutral", "Нейтрал"),
                            ("negative", "Негатив"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "snippet",
                    models.TextField(
                        blank=True, help_text="Фрагмент отзыва, который зацепил аспект"
                    ),
                ),
                (
                    "aspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="analysis.aspect",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspect_mentions",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["aspect", "label"],
                        name="analysis_as_aspect__b7cc54_idx",
                    )
                ],
                "unique_together": {("review", "aspect")},
            },
        ),
        migrations.CreateModel(
            name="SentimentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("positive", "Позитив"),
                            ("neutral", "Нейтрал"),
                            ("negative", "Негатив"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score", models.FloatField(help_text="Уверенность модели 0..1")),
                (
                    "model_name",
                    models.CharField(
                        help_text="Какая модель проставила метку", max_length=200
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_result",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат сентимента",
                "verbose_name_plural": "Результаты сентимента",
                "indexes": [
                    models.Index(fields=["label"], name="analysis_se_label_8af320_idx")
                ],
            },
        ),
    ]
