# Generated by Django 5.1.4 on 2026-05-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID отзыва на источнике", max_length=120
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=200)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1–5 звёзд", null=True
                    ),
                ),
                ("text", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("uz", "Oʻzbekcha (lotin)"),
                            ("uz_cyr", "Ўзбекча (кирилл)"),
                            ("ru", "Русский"),
                            ("kaa", "Qaraqalpaqsha"),
                            ("unk", "Unknown"),
                        ],
                        default="unk",
                        max_length=10,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-posted_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "posted_at"],
                        name="reviews_rev_product_6190c6_idx",
                    ),
                    models.Index(
                        fields=["language"], name="reviews_rev_languag_aa1181_idx"
                    ),
                ],
                "unique_together": {("product", "external_id")},
            },
        ),
    ]
