# Generated by Django 5.1.4 on 2026-05-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("uzum", "Uzum Market"),
                            ("asaxiy", "Asaxiy"),
                            ("texnomart", "Texnomart"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID товара на маркетплейсе", max_length=100
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "rating_avg",
                    models.FloatField(
                        blank=True, help_text="Средняя оценка маркетплейса", null=True
                    ),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "indexes": [
                    models.Index(
                        fields=["source", "external_id"],
                        name="products_pr_source_3d1da8_idx",
                    )
                ],
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
